#!/usr/bin/env python3
"""
VitalDB surgery-duration preprocessing pipeline (v1).

Goal: turn the raw VitalDB clinical + lab CSVs into a clean, leakage-safe,
canonical feature table for a downstream surgery-DURATION model. The eventual
model will emit a full duration CDF for OR-scheduling (newsvendor) decisions;
this script only does preprocessing.

Contract:
  * READ only from  ~/Desktop/vitaldb_work/
  * WRITE only to   ~/Desktop/vitaldb_work/processed/
  * NEVER touch     ~/Desktop/vitaldb/   (verified by checksum by the caller)

Every non-trivial design decision is logged to processed/decisions_log.md as we
go. That file is the primary deliverable for review.

Run:  python3 preprocess.py
"""

import hashlib
import json
import pickle
from pathlib import Path

import numpy as np
import pandas as pd
import yaml
from sklearn.preprocessing import StandardScaler

# --------------------------------------------------------------------------- #
# Paths
# --------------------------------------------------------------------------- #
WORK = Path.home() / "Desktop" / "vitaldb_work"
OUT = WORK / "processed"
OUT.mkdir(parents=True, exist_ok=True)

CLINICAL_CSV = WORK / "clinical_data.csv"
LAB_CSV = WORK / "lab_data.csv"

# decisions_log.md is streamed to as we go.
_LOG_LINES = []


def log(md: str = ""):
    """Append a line to the decisions log AND echo a compact version to stdout."""
    _LOG_LINES.append(md)


def decision(title, choice, alternatives, why):
    """Structured design-decision block -> decisions_log.md."""
    _LOG_LINES.append(f"\n### {title}")
    _LOG_LINES.append(f"- **Choice:** {choice}")
    _LOG_LINES.append(f"- **Alternatives considered:** {alternatives}")
    _LOG_LINES.append(f"- **Why:** {why}")
    # short form to stdout for live visibility
    print(f"  [decision] {title}: {choice}")


DECISION_SHORT = []  # short-form list for the final stdout summary


def note_decision(short):
    DECISION_SHORT.append(short)


# --------------------------------------------------------------------------- #
log("# VitalDB Surgery-Duration Preprocessing — Decisions Log")
log("")
log("_Generated by `preprocess.py`. Read this top-to-bottom; it records every "
    "non-trivial choice, the alternatives, and the reasoning._")
log("")
log("**Downstream use:** v1 preprocessing for a model that will output a full "
    "duration CDF for OR-scheduling (newsvendor) decisions. Preprocessing only "
    "— no model is trained here.")

# =========================================================================== #
# STAGE 1 — LOAD & INVENTORY
# =========================================================================== #
print("\n=== STAGE 1: Load & inventory ===")
log("\n---\n\n## Stage 1 — Load & inventory")

# The clinical CSV has a UTF-8 BOM on the first header cell; strip it.
clin = pd.read_csv(CLINICAL_CSV)
clin.columns = [c.replace("﻿", "").strip() for c in clin.columns]

lab = pd.read_csv(LAB_CSV)

# `age` is deidentified: patients over 89 are recorded as the string ">89"
# (HIPAA-style top-coding). Map ">89" -> 90 (a floor for the 90+ band) and
# coerce to numeric so the column is usable and the null-checks are meaningful.
# Logged as a decision below in Stage 4 (age handling).
_age_topcoded = int((clin["age"].astype(str).str.strip() == ">89").sum())
clin["age"] = pd.to_numeric(
    clin["age"].astype(str).str.strip().replace(">89", "90"), errors="coerce")

n_cases = len(clin)
print(f"Cases (rows in clinical_data): {n_cases}")
print(f"Columns in clinical_data: {clin.shape[1]}")
print(f"Lab rows: {len(lab)}  | distinct labs: {lab['name'].nunique()}")

log(f"\n- **Cases:** {n_cases} (one row per surgical case)")
log(f"- **Clinical columns:** {clin.shape[1]}")
log(f"- **Lab rows:** {len(lab):,} across {lab['name'].nunique()} distinct analytes, "
    f"{lab['caseid'].nunique()} cases")

# --- Time range. casestart is anonymized to 0 for EVERY case, so there is NO
# --- wall-clock timeline. All event times (anestart/opstart/opend/aneend, lab dt)
# --- are SECONDS RELATIVE to casestart(=0). We report the relative ranges.
log("\n### Time fields (all relative to `casestart`, which is 0 for every case)")
log(f"- `casestart` distinct values: {clin['casestart'].nunique()} "
    f"(value(s): {sorted(clin['casestart'].unique())[:3]}) — "
    "**wall-clock time is destroyed by anonymization.**")
for col in ["anestart", "opstart", "opend", "aneend"]:
    s = clin[col]
    log(f"- `{col}` (sec from casestart): min={s.min():.0f}, median={s.median():.0f}, "
        f"max={s.max():.0f}, nulls={s.isna().sum()}")
log(f"- lab `dt` (sec from casestart): min={lab['dt'].min():.0f}, "
    f"max={lab['dt'].max():.0f}")

# --- Missingness per clinical column (report the ones that actually have gaps).
miss = clin.isna().mean().sort_values(ascending=False)
log("\n### Missingness per clinical column (fraction missing, columns >0% only)")
log("")
log("| column | frac_missing |")
log("|---|---|")
for c, frac in miss[miss > 0].items():
    log(f"| {c} | {frac:.3f} |")
print(f"Columns with any missingness: {(miss > 0).sum()} / {clin.shape[1]}")

# --- Distinct-value counts for the categoricals we care about.
cat_cols = ["sex", "asa", "emop", "department", "optype", "opname",
            "approach", "position", "ane_type", "preop_htn", "preop_dm",
            "preop_ecg", "preop_pft"]
log("\n### Distinct-value counts for key categoricals")
log("")
log("| column | n_distinct | top values |")
log("|---|---|---|")
for c in cat_cols:
    if c in clin.columns:
        vc = clin[c].value_counts(dropna=False)
        top = "; ".join(f"{k}={v}" for k, v in vc.head(4).items())
        log(f"| {c} | {clin[c].nunique(dropna=False)} | {top} |")

# --- Obvious anomalies discovered during inventory.
op_dur_raw = (clin["opend"] - clin["opstart"]) / 60.0
ane_dur_raw = (clin["aneend"] - clin["anestart"]) / 60.0
anomalies = []
anomalies.append(f"`casestart`==0 for all {n_cases} cases → no absolute date/time; "
                 "time-of-day & day-of-week are NOT recoverable from this release.")
anomalies.append(f"Anesthesia duration (aneend-anestart) has {int((ane_dur_raw<=0).sum())} "
                 f"non-positive and {int((ane_dur_raw>1440).sum())} >24h value(s); "
                 f"min={ane_dur_raw.min():.0f} min — clearly corrupt timestamps.")
anomalies.append(f"Operation duration (opend-opstart) is clean: min={op_dur_raw.min():.1f}, "
                 f"max={op_dur_raw.max():.1f} min, no non-positive, no >24h, no nulls.")
anomalies.append(f"`asa` has {int(clin['asa'].isna().sum())} nulls and includes ASA=6 "
                 f"({int((clin['asa']==6).sum())} cases = brain-dead organ donors).")
anomalies.append("Lab `name` includes standard analytes (hct, k, na, hb, ...); lab `dt` "
                 "spans ±7.7M sec (~±90 days) around casestart, i.e. long pre/post history.")
log("\n### Obvious anomalies")
for a in anomalies:
    log(f"- {a}")
    print(f"  [anomaly] {a}")

# =========================================================================== #
# STAGE 2 — DEFINE THE LABEL
# =========================================================================== #
print("\n=== STAGE 2: Define label (duration_minutes) ===")
log("\n---\n\n## Stage 2 — Label definition")

decision(
    "Which timestamps define the duration label",
    "SURGICAL time: `duration_minutes = (opend - opstart) / 60`.",
    "(a) Anesthesia time `aneend - anestart`; (b) EMR-provided `opdur`/`anedur`; "
    "(c) `caseend - casestart` recording length.",
    "Three reasons. (1) **Consistency with the leakage boundary:** the task fixes "
    "the feature cutoff at `opstart`, so the natural quantity to predict is the "
    "time that elapses AFTER `opstart` — i.e. operation time. Anesthesia time "
    "starts at `anestart` (< opstart), which would put the label's clock partly "
    "inside the feature window and muddy the leakage contract. (2) **Data quality:** "
    "operation time is clean here (min 1.4, max 955 min, zero non-positive, zero "
    ">24h, zero nulls), whereas anesthesia time has corrupt rows (a negative "
    "-61.5M-min value and a >24h value). (3) **Semantics:** the project is 'surgery "
    "duration prediction'; operation start→end is the surgical procedure itself. "
    "Anesthesia time (incl. induction/emergence) is more OR-occupancy than 'surgery' "
    "and is the better *alternative* to revisit for a room-turnover model — noted "
    "for v2.",
)
note_decision("Label = operation time (opend-opstart), not anesthesia time.")

clin["duration_minutes"] = (clin["opend"] - clin["opstart"]) / 60.0

# --- Drop impossible label values. Report counts.
decision(
    "Impossible-label filter",
    "Drop rows where duration is null, <= 0, or > 1440 min (24h).",
    "Keep and cap extreme durations; or use a tighter cap (e.g. 12h).",
    "Non-positive/null durations are corrupt timestamps and cannot be a valid "
    "target. 24h is a generous physical ceiling for a single OR case; anything "
    "beyond it is a timestamp error rather than a real surgery. A tighter cap "
    "(12h) risks discarding genuine long cases (this cohort has a real 955-min "
    "case), so we use the conservative 24h ceiling here and handle the upper "
    "TAIL via winsorized features later — never by dropping real long surgeries.",
)
before = len(clin)
bad_null = clin["duration_minutes"].isna()
bad_nonpos = clin["duration_minutes"] <= 0
bad_over = clin["duration_minutes"] > 1440
label_bad = bad_null | bad_nonpos | bad_over
clin = clin[~label_bad].copy()
log(f"\n- Rows before label filter: {before}")
log(f"- Dropped null duration: {int(bad_null.sum())}")
log(f"- Dropped non-positive duration: {int(bad_nonpos.sum())}")
log(f"- Dropped >24h duration: {int(bad_over.sum())}")
log(f"- Rows after label filter: {len(clin)}")
print(f"Label filter dropped {before - len(clin)} rows -> {len(clin)} remain")

# =========================================================================== #
# STAGE 3 — COHORT FILTERING
# =========================================================================== #
print("\n=== STAGE 3: Cohort filtering ===")
log("\n---\n\n## Stage 3 — Cohort filtering")
log("\nEvery exclusion rule is applied in sequence; the table below logs the rows "
    "dropped by each rule (rules are evaluated on the surviving cohort, so counts "
    "are sequential, not independent).")

filter_rows = []  # (rule, dropped, remaining)


def apply_filter(mask_drop, rule_name):
    """mask_drop is True for rows to REMOVE (aligned to current clin index)."""
    global clin
    dropped = int(mask_drop.sum())
    clin = clin[~mask_drop].copy()
    filter_rows.append((rule_name, dropped, len(clin)))
    print(f"  [filter] {rule_name}: -{dropped} -> {len(clin)}")


start_cohort = len(clin)

# Rule 1: local/monitored-anesthesia-only cases are out of scope. In VitalDB the
# 'Sedationalgesia' ane_type is MAC/sedation (no general/regional surgical
# anesthesia) — these behave differently and are the closest analog to the
# "local anesthesia only" exclusion the brief calls for.
decision(
    "Anesthesia-type cohort",
    "Keep `General` and `Spinal`; exclude `Sedationalgesia` (MAC/sedation).",
    "Keep only `General`; or keep all three.",
    "Sedation/MAC ('Sedationalgesia') is the local-anesthesia-care analog the "
    "brief asks us to exclude — different workflow, poorly-defined operative "
    "phase. `Spinal` is genuine surgical (neuraxial/regional) anesthesia with a "
    "well-defined operation and is kept. Keeping only `General` would needlessly "
    "drop 273 legitimate regional cases.",
)
note_decision("Cohort: keep General+Spinal anesthesia; drop Sedationalgesia (local/MAC).")
apply_filter(clin["ane_type"].eq("Sedationalgesia") | clin["ane_type"].isna(),
             "ane_type is Sedationalgesia or null (local/MAC or unknown)")

# Rule 2: ASA 6 = declared brain-dead organ donors (organ-harvest cases). These
# are out of scope for elective/urgent surgery scheduling and have atypical
# duration profiles.
decision(
    "ASA physical-status scope",
    "Exclude ASA == 6 (brain-dead organ donors).",
    "Keep all ASA classes; or also exclude ASA 5 (moribund) — none present here.",
    "ASA 6 are organ-procurement cases, not scheduled therapeutic surgery; their "
    "duration distribution is driven by harvest logistics, not the patient/"
    "procedure features we model. Excluding them keeps the target population "
    "coherent. ASA nulls are NOT dropped here — ASA is imputed with a flag in "
    "Stage 4 to avoid discarding otherwise-complete cases.",
)
note_decision("Cohort: exclude ASA 6 (organ donors).")
apply_filter(clin["asa"].eq(6), "ASA == 6 (organ-donor / harvest cases)")

# Rule 3: incomplete core records — missing any of the fields the label or the
# minimal patient descriptor depend on. (Label already guaranteed non-null; here
# we require age & sex, the irreducible patient identifiers.)
decision(
    "Incomplete-record filter",
    "Require non-null `age` and `sex`.",
    "Also require non-null height/weight/BMI and all labs.",
    "Age and sex are the minimal, near-universal patient descriptors and are "
    "cheap to require. We deliberately do NOT require height/weight/BMI, ASA, or "
    "labs to be present — those are imputed with missingness flags (Stage 4) so "
    "we retain cases that are otherwise informative. Dropping on every field "
    "would shrink the cohort and bias it toward fully-documented (often sicker/"
    "work-up-heavy) patients.",
)
note_decision("Cohort: require non-null age & sex; other fields imputed not dropped.")
apply_filter(clin["age"].isna() | clin["sex"].isna(),
             "age or sex is null (incomplete core record)")

# Rule 4: obvious data errors on the physical measurements used for BMI. Guard
# against impossible height/weight that would produce nonsense BMI. We CAP rather
# than drop in Stage 4, but rows with height/weight both missing AND no provided
# bmi cannot yield a BMI at all — still kept (BMI imputed), so no drop here.
# (No additional drop rule; documented for transparency.)
log("\n- (No separate drop for height/weight errors — implausible values are "
    "capped and BMI is imputed in Stage 4 rather than dropped.)")

log("\n### Filtering summary table")
log("")
log("| rule | rows dropped | rows remaining |")
log("|---|---|---|")
log(f"| (start of Stage 3) | 0 | {start_cohort} |")
for rule, dropped, remaining in filter_rows:
    log(f"| {rule} | {dropped} | {remaining} |")
log(f"\n**Cohort after filtering: {len(clin)} cases** "
    f"(from {start_cohort} at start of Stage 3).")

# =========================================================================== #
# STAGE 4 — FEATURE ENGINEERING INTO CANONICAL SCHEMA
# =========================================================================== #
print("\n=== STAGE 4: Feature engineering ===")
log("\n---\n\n## Stage 4 — Feature engineering (canonical schema)")
log("\n**Leakage discipline:** a feature may use only information knowable BEFORE "
    "`opstart`. Preop labs, comorbidities, patient demographics, the *scheduled* "
    "procedure descriptors, and the *planned* start clock are allowed. Anything "
    "measured/occurring at or after `opstart` (postop labs, intraop drugs/fluids, "
    "EBL, outcomes, the duration itself) is FORBIDDEN and never read into features.")

feat = pd.DataFrame(index=clin.index)
feat["caseid"] = clin["caseid"].values

# ---- Patient block -------------------------------------------------------- #
decision(
    "Age de-identification top-coding",
    f"Map the de-identified string age '>89' -> 90 ({_age_topcoded} cases), keep "
    "age numeric.",
    "Drop >89 cases; or map to 89 / 95 / a separate 'elderly' flag.",
    "Ages 90+ are top-coded to '>89' for anonymity. Mapping to 90 (the band "
    "floor) preserves the case and its monotonic age signal with minimal "
    "distortion; the exact value in a 90+ band matters little for duration and "
    "these are few. Dropping them would bias the cohort younger.",
)
note_decision(f"Age: de-identified '>89' mapped to 90 ({_age_topcoded} cases).")
feat["age"] = clin["age"].astype(float)
feat["sex"] = clin["sex"].astype("string")  # 'M'/'F', encoded later

# BMI: recompute from height/weight (authoritative); fall back to provided bmi.
decision(
    "BMI source",
    "Recompute `bmi = weight / (height/100)^2`; fall back to provided `bmi` "
    "column when height or weight is missing; then cap to [10, 70].",
    "Trust the provided `bmi` column outright; or drop rows with bad BMI.",
    "Recomputing from height/weight is transparent and lets us sanity-check the "
    "provided column. The [10, 70] cap removes physically impossible BMIs "
    "(data-entry errors) without discarding the case — the patient's other "
    "features are still useful. Values outside the range are clipped to the "
    "bound, and truly-missing BMI is median-imputed with a flag (below).",
)
note_decision("BMI recomputed from height/weight, capped [10,70], fallback to bmi col.")
bmi_calc = clin["weight"] / (clin["height"] / 100.0) ** 2
bmi = bmi_calc.where(bmi_calc.notna(), clin["bmi"])
feat["bmi"] = bmi.clip(lower=10, upper=70)

# ASA: ordinal 1..5. Kept numeric; nulls imputed (train median) with a flag.
feat["asa"] = clin["asa"].astype(float)

# ---- Procedure block ------------------------------------------------------ #
feat["department"] = clin["department"].astype("string")
feat["optype"] = clin["optype"].astype("string")
feat["opname"] = clin["opname"].astype("string")   # high-cardinality (241)
feat["approach"] = clin["approach"].astype("string")
feat["position"] = clin["position"].astype("string")
feat["ane_type"] = clin["ane_type"].astype("string")
feat["emergency"] = clin["emop"].astype("float")    # 0/1 flag

# Preop comorbidity flags — recorded before surgery, safe features w/ real signal.
feat["preop_htn"] = clin["preop_htn"].astype("float")
feat["preop_dm"] = clin["preop_dm"].astype("float")

# ---- Preop labs from lab_data (time-windowed, most-recent-before-opstart) -- #
decision(
    "Preop-lab join: window and aggregation",
    "For each case and each key analyte, take the MOST RECENT lab with "
    "`dt < opstart` AND `dt >= opstart - 30 days`. 30-day window; strictly "
    "before opstart.",
    "(a) Use clinical_data's preop_* columns directly; (b) 7-day window; "
    "(c) 90-day window; (d) mean/min/max over the window instead of most-recent.",
    "We build labs from lab_data (not the convenient preop_* columns) because the "
    "brief asks for an explicit, auditable time-windowed join that future data "
    "sources can reproduce. **Strictly `dt < opstart`** enforces leakage safety "
    "(a lab drawn exactly at/after incision is excluded). **30 days** matches "
    "standard preoperative work-up validity: routine preop labs are drawn within "
    "days-to-weeks of surgery; 7 days is too tight (misses clinic labs from the "
    "prior visit and inflates missingness), 90 days risks stale physiology. "
    "**Most-recent** (vs mean) reflects the value the anesthesiologist actually "
    "sees at scheduling and avoids blending stale with fresh draws.",
)
note_decision("Preop labs: most-recent lab in [opstart-30d, opstart), from lab_data.")

KEY_LABS = ["hb", "hct", "wbc", "plt", "na", "k", "gluc",
            "cr", "bun", "alb", "ast", "alt", "ptinr", "aptt"]
WINDOW_SEC = 30 * 24 * 3600  # 30 days

# opstart per case (relative seconds). Join opstart onto the (kept) cohort's labs.
op_lookup = clin.set_index("caseid")["opstart"]
lab_k = lab[lab["name"].isin(KEY_LABS)].copy()
lab_k = lab_k[lab_k["caseid"].isin(op_lookup.index)]
lab_k["opstart"] = lab_k["caseid"].map(op_lookup)
lab_k["result"] = pd.to_numeric(lab_k["result"], errors="coerce")
# leakage-safe window: strictly before opstart, within 30 days
in_win = (lab_k["dt"] < lab_k["opstart"]) & (lab_k["dt"] >= lab_k["opstart"] - WINDOW_SEC)
lab_win = lab_k[in_win & lab_k["result"].notna()].copy()
# most-recent = max dt per (caseid, name)
lab_win = lab_win.sort_values("dt").groupby(["caseid", "name"], as_index=False).last()
lab_wide = lab_win.pivot(index="caseid", columns="name", values="result")
lab_wide = lab_wide.reindex(columns=KEY_LABS)  # guarantee all columns exist
lab_wide.columns = [f"lab_{c}" for c in lab_wide.columns]

feat = feat.merge(lab_wide, left_on="caseid", right_index=True, how="left")
lab_feat_cols = [f"lab_{c}" for c in KEY_LABS]
lab_cov = feat[lab_feat_cols].notna().mean()
log("\n### Preop-lab coverage (fraction of cohort with a value in-window)")
log("")
log("| lab | coverage |")
log("|---|---|")
for c in lab_feat_cols:
    log(f"| {c} | {lab_cov[c]:.3f} |")

# ---- Time-of-day / day-of-week (STRUCTURAL PLACEHOLDERS) ------------------ #
decision(
    "Time-of-day / day-of-week features",
    "Add `op_hour` and `op_dow` to the schema but leave them NULL in this "
    "release.",
    "Fabricate them from the relative `opstart` seconds; or omit the columns.",
    "`casestart` is anonymized to 0 for every case, so `opstart` is a seconds-"
    "offset into the recording, NOT a wall-clock time — real hour-of-day and "
    "day-of-week are unrecoverable. Fabricating them would inject noise/false "
    "signal. We keep the columns as typed nullable placeholders so a future, "
    "non-anonymized data source (which the brief anticipates) plugs in without a "
    "schema change — the same pattern used for staff features below. Note: the "
    "*planned* start clock IS a legitimate pre-opstart feature in principle; it "
    "is simply not present in this dataset.",
)
note_decision("op_hour/op_dow: schema placeholders (null) — casestart anonymized to 0.")
feat["op_hour"] = pd.array([pd.NA] * len(feat), dtype="Float64")
feat["op_dow"] = pd.array([pd.NA] * len(feat), dtype="Int64")

# ---- Staff features (STRUCTURAL PLACEHOLDERS) ----------------------------- #
decision(
    "Staff features",
    "Add nullable `surgeon_id` and `surgeon_case_count_for_this_procedure` "
    "columns, both NULL in this release.",
    "Omit them until a data source exists.",
    "VitalDB is anonymized with no surgeon identifiers. The brief explicitly "
    "wants these columns present so future data (with surgeon IDs) plugs in "
    "cleanly. `surgeon_case_count_for_this_procedure` is a surgeon×procedure "
    "experience proxy that will need a leakage-safe, time-ordered count when "
    "real data arrives.",
)
note_decision("surgeon_id + surgeon_case_count: nullable placeholders for future data.")
feat["surgeon_id"] = pd.array([pd.NA] * len(feat), dtype="string")
feat["surgeon_case_count_for_this_procedure"] = pd.array([pd.NA] * len(feat), dtype="Int64")

# ---- The label travels with the feature table (kept separate from features) #
feat["duration_minutes"] = clin["duration_minutes"].values

print(f"Feature table assembled: {feat.shape[0]} rows x {feat.shape[1]} cols "
      f"(incl. caseid + label)")

# =========================================================================== #
# STAGE 5 — SPLIT BY TIME
# =========================================================================== #
print("\n=== STAGE 5: Split (by time) ===")
log("\n---\n\n## Stage 5 — Train/Val/Test split")

decision(
    "Split strategy and ordering key",
    "Chronological 70/15/15 split. Ordering key = `caseid` ascending (earliest "
    "70% -> train, next 15% -> val, latest 15% -> test).",
    "(a) Random split; (b) grouped split by subjectid; (c) refuse to split for "
    "lack of a timestamp.",
    "A scheduling model is deployed forward in time, so the split MUST be "
    "temporal to give an honest generalization estimate and avoid train/test "
    "leakage of era effects. BUT this release has no wall-clock timestamp "
    "(`casestart`==0). `caseid` (1..6388) is the only monotonic case ordering "
    "available and is used as the temporal proxy: test = highest caseids. "
    "**Caveat (logged loudly):** the data dictionary describes caseid as a random "
    "number, so this proxy may not be truly chronological — when real timestamps "
    "arrive, swap the ordering key here and the rest of the pipeline is unchanged. "
    "This is strictly better than a random split (never mixes a 'future' case "
    "into train) and keeps the mechanism correct. Encoders/scalers/imputers are "
    "fit on TRAIN ONLY to prevent leakage across the boundary.",
)
note_decision("Split: chronological 70/15/15 by caseid ascending (temporal proxy; "
              "swap key when real timestamps exist).")

order = feat.sort_values("caseid")
ids = order["caseid"].tolist()
n = len(ids)
n_train = int(n * 0.70)
n_val = int(n * 0.15)
train_ids = ids[:n_train]
val_ids = ids[n_train:n_train + n_val]
test_ids = ids[n_train + n_val:]
log(f"\n- Total cohort: {n}")
log(f"- Train: {len(train_ids)} (caseid {train_ids[0]}..{train_ids[-1]})")
log(f"- Val:   {len(val_ids)} (caseid {val_ids[0]}..{val_ids[-1]})")
log(f"- Test:  {len(test_ids)} (caseid {test_ids[0]}..{test_ids[-1]})")
print(f"Split -> train {len(train_ids)} | val {len(val_ids)} | test {len(test_ids)}")

train_mask = feat["caseid"].isin(train_ids)

# =========================================================================== #
# STAGE 4b — MISSING-VALUE HANDLING, OUTLIER CAPS, ENCODING (fit on TRAIN)
# (done after the split so all fitting is train-only — leakage-safe)
# =========================================================================== #
print("\n=== STAGE 4b: Impute / cap / encode (fit on TRAIN only) ===")
log("\n---\n\n## Stage 4b — Imputation, outlier caps, encoding (fit on TRAIN only)")

encoders = {"meta": {"fit_on": "train split only", "n_train": int(train_mask.sum())}}

# ---- Numeric outlier caps (winsorize) ------------------------------------ #
decision(
    "Numeric outlier handling",
    "Winsorize labs + age + bmi at TRAIN 0.5th/99.5th percentiles (clip, don't "
    "drop). BMI additionally hard-capped to [10,70] earlier.",
    "Drop outlier rows; z-score trimming; or no capping.",
    "Clipping preserves every case (rows are scarce and each carries a valid "
    "label) while taming data-entry spikes that would distort scalers and any "
    "distance/linear component of the downstream model. 0.5/99.5 is gentle — it "
    "touches only the extreme tails. Percentiles are computed on TRAIN ONLY and "
    "then applied to val/test, so no test information leaks into the caps.",
)
note_decision("Outliers: winsorize labs/age/bmi at train 0.5/99.5 pctile (clip).")

winsor_cols = ["age", "bmi"] + lab_feat_cols
caps = {}
for c in winsor_cols:
    lo = feat.loc[train_mask, c].quantile(0.005)
    hi = feat.loc[train_mask, c].quantile(0.995)
    if pd.notna(lo) and pd.notna(hi) and lo < hi:
        feat[c] = feat[c].clip(lo, hi)
        caps[c] = (float(lo), float(hi))
encoders["winsor_caps"] = caps

# ---- Missing-value imputation (train median) + missingness flags ---------- #
decision(
    "Missing-value strategy for numeric features",
    "Median-impute (TRAIN median) every numeric feature that has gaps AND add a "
    "companion `<col>_missing` 0/1 indicator column.",
    "Drop rows with any missing; model-native NaN handling; mean imputation.",
    "Median is robust to skew (labs, BMI are skewed). Missingness in preop labs "
    "is itself informative (a lab not ordered often signals a low-acuity case), "
    "so we preserve that signal explicitly with indicator columns rather than "
    "letting imputation erase it. Row-dropping would gut lab coverage; we keep "
    "the table model-ready (no NaNs in the numeric block) while retaining the "
    "signal. Train-median keeps the fit leakage-safe.",
)
note_decision("Missing numerics: train-median impute + <col>_missing indicator flags.")

impute_num = ["age", "bmi", "asa", "emergency", "preop_htn", "preop_dm"] + lab_feat_cols
medians = {}
for c in impute_num:
    med = feat.loc[train_mask, c].median()
    flag = feat[c].isna().astype("int8")
    if flag.sum() > 0:
        feat[f"{c}_missing"] = flag
    feat[c] = feat[c].fillna(med)
    medians[c] = float(med) if pd.notna(med) else None
encoders["train_medians"] = medians

# ---- Categorical encoding (fit on TRAIN; rare-group high-cardinality) ------ #
decision(
    "Categorical encoding",
    "Integer/ordinal label-encoding fit on TRAIN. `opname` (241 levels) is "
    "rare-grouped: levels seen <10x in train collapse to 'Other'. Unseen "
    "val/test levels and nulls map to a reserved code (-1). Mappings saved to "
    "encoders.pkl.",
    "One-hot encoding; target/mean encoding; leave as raw strings.",
    "The downstream CDF model will almost certainly be gradient-boosted trees "
    "(native support for integer-coded categoricals), so compact label codes are "
    "ideal and avoid one-hot blow-up from 241 opnames. Rare-grouping controls "
    "cardinality and overfitting on singleton procedures. Target encoding was "
    "rejected for v1 because it needs careful out-of-fold handling to avoid label "
    "leakage — deferred to the modeling stage. Reserved -1 for unseen/null keeps "
    "inference robust to new categories.",
)
note_decision("Categoricals: train-fit label encoding; opname rare-grouped (<10 -> "
              "Other); unseen/null -> -1.")

cat_features = ["sex", "department", "optype", "approach", "position",
                "ane_type", "opname"]
cat_maps = {}
RARE_MIN = 10
for c in cat_features:
    col = feat[c].astype("string")
    train_vals = col[train_mask]
    if c == "opname":
        vc = train_vals.value_counts()
        keep = set(vc[vc >= RARE_MIN].index)
        col = col.where(col.isin(keep), other="Other")
        train_vals = col[train_mask]
    levels = sorted([v for v in train_vals.dropna().unique()])
    mapping = {v: i for i, v in enumerate(levels)}  # 0..k-1; -1 reserved
    cat_maps[c] = mapping
    feat[c] = col.map(mapping).fillna(-1).astype("int32")
encoders["categorical_maps"] = cat_maps
encoders["categorical_unknown_code"] = -1
encoders["opname_rare_min_count"] = RARE_MIN

# ---- Scaler for the numeric block (fit on TRAIN; saved, NOT applied) ------- #
decision(
    "Feature scaling",
    "Fit a `StandardScaler` on the TRAIN numeric block and SAVE it to "
    "encoders.pkl, but store UNSCALED values in features.parquet.",
    "Pre-scale the parquet; or skip scaling entirely.",
    "Tree models don't need scaling, but a linear/NN CDF head or quantile "
    "regressor might. Saving the fitted scaler (train-only) lets the modeler "
    "apply it deterministically if needed, while keeping the persisted table "
    "human-readable and model-agnostic. Storing unscaled values avoids baking one "
    "model's assumptions into the shared artifact.",
)
note_decision("Scaling: StandardScaler fit on train numerics, saved not applied; "
              "parquet stays unscaled.")

scaler_cols = ["age", "bmi", "asa"] + lab_feat_cols
scaler = StandardScaler()
scaler.fit(feat.loc[train_mask, scaler_cols].values)
encoders["scaler"] = scaler
encoders["scaler_columns"] = scaler_cols

# =========================================================================== #
# STAGE 6 — PERSIST
# =========================================================================== #
print("\n=== STAGE 6: Persist artifacts ===")
log("\n---\n\n## Stage 6 — Persisted artifacts")

# Order columns: id, features, label. Keep label out of the "feature" list.
id_col = ["caseid"]
label_col = ["duration_minutes"]
missing_flag_cols = [c for c in feat.columns if c.endswith("_missing")]
feature_cols = [c for c in feat.columns
                if c not in id_col + label_col]
feat = feat[id_col + feature_cols + label_col]

# --- features.parquet
features_path = OUT / "features.parquet"
feat.to_parquet(features_path, index=False)

# --- encoders.pkl
encoders_path = OUT / "encoders.pkl"
with open(encoders_path, "wb") as f:
    pickle.dump(encoders, f)

# --- splits.json
splits = {
    "strategy": "chronological_by_caseid_proxy",
    "ratios": {"train": 0.70, "val": 0.15, "test": 0.15},
    "caveat": ("casestart anonymized to 0; caseid used as temporal proxy. Swap "
               "ordering key for real timestamps when available."),
    "train": [int(x) for x in train_ids],
    "val": [int(x) for x in val_ids],
    "test": [int(x) for x in test_ids],
}
splits_path = OUT / "splits.json"
with open(splits_path, "w") as f:
    json.dump(splits, f, indent=2)

# --- schema.yaml  (canonical name -> dtype + source mapping)
def dtype_str(col):
    return str(feat[col].dtype)


SOURCE_MAP = {
    "caseid": "clinical_data.caseid (identifier)",
    "age": "clinical_data.age",
    "sex": "clinical_data.sex (label-encoded)",
    "bmi": "derived: weight/(height/100)^2, fallback clinical_data.bmi, capped [10,70]",
    "asa": "clinical_data.asa (ordinal 1-5)",
    "department": "clinical_data.department (label-encoded)",
    "optype": "clinical_data.optype (label-encoded)",
    "opname": "clinical_data.opname (label-encoded, rare-grouped)",
    "approach": "clinical_data.approach (label-encoded)",
    "position": "clinical_data.position (label-encoded)",
    "ane_type": "clinical_data.ane_type (label-encoded)",
    "emergency": "clinical_data.emop (0/1)",
    "preop_htn": "clinical_data.preop_htn (0/1)",
    "preop_dm": "clinical_data.preop_dm (0/1)",
    "op_hour": "PLACEHOLDER (null): unrecoverable, casestart anonymized to 0",
    "op_dow": "PLACEHOLDER (null): unrecoverable, casestart anonymized to 0",
    "surgeon_id": "PLACEHOLDER (null): VitalDB anonymized, no surgeon IDs",
    "surgeon_case_count_for_this_procedure": "PLACEHOLDER (null): future data source",
    "duration_minutes": "LABEL: (opend-opstart)/60",
}
for c in lab_feat_cols:
    SOURCE_MAP[c] = (f"lab_data: most-recent '{c[4:]}' with "
                     f"opstart-30d <= dt < opstart (leakage-safe)")
for c in missing_flag_cols:
    SOURCE_MAP[c] = f"missingness indicator for {c[:-8]} (1=was missing, median-imputed)"

schema = {
    "dataset": "VitalDB surgery-duration preprocessing v1",
    "label": {
        "name": "duration_minutes",
        "definition": "(opend - opstart) / 60",
        "unit": "minutes",
    },
    "leakage_rule": "no feature derived from information at/after opstart",
    "columns": [],
}
for c in feat.columns:
    role = ("id" if c in id_col else "label" if c in label_col
            else "feature")
    schema["columns"].append({
        "name": c,
        "dtype": dtype_str(c),
        "role": role,
        "source": SOURCE_MAP.get(c, "clinical_data"),
    })
schema_path = OUT / "schema.yaml"
with open(schema_path, "w") as f:
    yaml.safe_dump(schema, f, sort_keys=False)

log(f"\n- `features.parquet` — {feat.shape[0]} rows x {feat.shape[1]} cols "
    f"({len(feature_cols)} features + caseid + label)")
log(f"- `encoders.pkl` — categorical maps, winsor caps, train medians, "
    f"StandardScaler (all fit on train)")
log(f"- `schema.yaml` — {len(schema['columns'])} canonical columns w/ dtype + source")
log(f"- `splits.json` — train/val/test caseid lists (chronological proxy)")
log("- `decisions_log.md` — this file")

print(f"Wrote: {features_path.name}, {encoders_path.name}, {schema_path.name}, "
      f"{splits_path.name}, decisions_log.md")

# --- Write the decisions log LAST (it accumulated throughout) --------------- #
log("\n---\n\n## Design-decision index (short form)")
for i, d in enumerate(DECISION_SHORT, 1):
    log(f"{i}. {d}")

with open(OUT / "decisions_log.md", "w") as f:
    f.write("\n".join(_LOG_LINES) + "\n")

# =========================================================================== #
# END-STATE SUMMARY (stdout)
# =========================================================================== #
print("\n" + "=" * 68)
print("PREPROCESSING COMPLETE — SUMMARY")
print("=" * 68)
print(f"Final cohort rows : {feat.shape[0]}")
print(f"Feature count     : {len(feature_cols)} (excludes caseid & label)")
print(f"  - incl. {len(missing_flag_cols)} missingness-indicator columns")
print(f"Label             : duration_minutes = (opend-opstart)/60  "
      f"[median {feat['duration_minutes'].median():.0f} min]")
print(f"Split (by time)   : train {len(train_ids)} | val {len(val_ids)} | "
      f"test {len(test_ids)}")
print("\nDesign decisions (details in processed/decisions_log.md):")
for i, d in enumerate(DECISION_SHORT, 1):
    print(f"  {i:>2}. {d}")
print("\nArtifacts in processed/:")
for p in ["features.parquet", "encoders.pkl", "schema.yaml", "splits.json",
          "decisions_log.md"]:
    print(f"  - {p}")

# --- raw-dir integrity check is done by the CALLER (checksum compare) so it
# --- sits outside this script's write scope; we print a reminder marker.
print("\n[raw-integrity check performed outside this script — see checksum compare]")
